# Cloud Build configuration for Google Cloud Functions
steps:
  # 0. DIAGNOSTICS: List files to make sure package.json is in place
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'ls -F']
    id: CHECK_FILES

  # 1. build step (now this is demo-echo.In real project here would be run npm install)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'echo "Starting build for $_FUNCTION_NAME in project $PROJECT_ID..."']
    id: BUILD

  # 2. Testing step
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'echo "Running tests..."']
    id: TEST

  # 3. DEPLOY: Deploying a function in Google Cloud Functions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - $_FUNCTION_NAME
      - --region=$_FUNCTION_REGION
      - --source=$_SOURCE_PATH
      - --trigger-http
      - --runtime=$_FUNCTION_RUNTIME
      - --entry-point=$_ENTRY_POINT
      #--project is usually not needed if the build is in the same project,
      # but we left it in for flexibility.
      - --project=$_PROJECT_ID
      # Allow unauthorized access for tests (optional)
      - --allow-unauthenticated
    id: DEPLOY

# if 'build.service_account' is specified, the build must either (a) specify 'build.logs_bucket'
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
    _PROJECT_ID : test-cloud-run-490713
    _FUNCTION_NAME    : my-nodejs-app
    _FUNCTION_REGION  : europe-west3
    # WARNING: Check your nodejs version. Currently stable: nodejs18, nodejs20, nodejs22.
    _FUNCTION_RUNTIME : nodejs22
    _ENTRY_POINT      : helloWorld
    _SOURCE_PATH      : ./my-app
