# Cloud Build configuration for Google Cloud Functions
steps:
  # 0. DIAGNOSTICS: List files to make sure package.json is in place
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'ls -Fl ./*']
    id: CHECK_FILES

  # 1. build step (now this is demo-echo.In real project here would be run npm install)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'echo "Starting build for $_FUNCTION_NAME in project $PROJECT_ID..."']
    id: BUILD

  # 2. Testing step
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'echo "Running tests..."']
    id: TEST

  # 3. DEPLOY: Deploying a function in Google Cloud Functions (2nd Gen)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - $_FUNCTION_NAME
      - --region=$_FUNCTION_REGION
      - --source=$_SOURCE_PATH
      - --trigger-http
      - --runtime=$_FUNCTION_RUNTIME
      - --entry-point=$_ENTRY_POINT
      # Деплоїмо без перемикання
      - --allow-unauthenticated
      #--project is usually not needed if the build is in the same project,
      # but we left it in for flexibility.
      - --project=$_PROJECT_ID
      # Allow unauthorized access for tests (optional)
      # doesn't work without Security Admin (roles/iam.securityAdmin)
      # - --allow-unauthenticated
      # Use a spec. account to execute the code
      - --service-account=func-runtime@$PROJECT_ID.iam.gserviceaccount.com
    id: 'Deploy Function'

  # Canary Deployment - traffic distribution between versions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Set Traffic Split'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Використовуємо $$, щоб Cloud Build ігнорував ці змінні
        LATEST_REV=$$(gcloud run revisions list --service my-nodejs-app --region europe-west3 --limit 1 --format="value(metadata.name)")
        PREV_REV=$$(gcloud run revisions list --service my-nodejs-app --region europe-west3 --limit 1 --offset=1 --format="value(metadata.name)")

        echo "Setting traffic: 10% to $$LATEST_REV and 90% to $$PREV_REV"

        gcloud run services update-traffic my-nodejs-app \
          --region europe-west3 \
          --to-revisions=$$LATEST_REV=10,$$PREV_REV=90

  # 4. Cleaning old images in the Artifact Registry (remaining the last 2)
  - name: 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
    id: 'Clean Old Images'
    args:
      - -repo=europe-west3-docker.pkg.dev/$PROJECT_ID/gcf-artifacts/my-nodejs-app
      - -keep=2
      - -tag-filter-any=.*

# if 'build.service_account' is specified, the build must either (a) specify 'build.logs_bucket'
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
    _PROJECT_ID : test-cloud-run-490713
    _FUNCTION_NAME    : my-nodejs-app
    _FUNCTION_REGION  : europe-west3
    # WARNING: Check your nodejs version. Currently stable: nodejs18, nodejs20, nodejs22.
    _FUNCTION_RUNTIME : nodejs22
    _ENTRY_POINT      : helloWorld
    _SOURCE_PATH      : ./my-app
